---

- hosts: 192.168.1.104
  become: yes
  become_user: root
  tasks:
    - name: ensure that id_rsa_slave is an authorized_key
      authorized_key:
        user: htpc
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Make sure we have a 'wheel' group
      group: name=wheel state=present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: Add htpc to wheel group
      user: name=htpc groups=wheel append=yes
    - name: Make mount point
      file: name=/mnt/media state=directory mode=0777
    - name: Mount media drive
      mount:
        path: /mnt/media
        src: UUID=6088F0A288F0783C
        fstype: ntfs
        opts: ntfs rw,auto,users,exec,nls=utf8,umask=003,gid=1000,uid=1000
        state: mounted
    - name: remove packages
      apt:
        name: gnome-screensaver
        state: absent
    # - name: Add google chrome apt key
    #   apt_key:
    #     url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    # - name: add extra apt repos
    #   apt_repository:
    #     repo: "{{ item }}"
    #   with_items:
    #     - "deb http://dl.google.com/linux/chrome/deb/ stable main"
    #     - ppa:team-xbmc/ppa
    #     - ppa:transmissionbt/ppa
    - name: Update repositories cache and install google chrome
      apt:
        name:
        - aptitude
        - google-chrome-stable
        - kodi
        - software-properties-common
        - transmission-cli
        - transmission-common
        - transmission-daemon
        - xscreensaver
        - xscreensaver-data-extra
        - xscreensaver-gl-extra
        update_cache: yes
      register: apt
    - debug: var=apt
    - name: Add htpc to debian-transmission group
      user: name=htpc groups=debian-transmission append=yes
    - name: Add debian-transmission to htpc group
      user: name=debian-transmission groups=htpc append=yes
    - name: set dirname for transmission-daemon
      set_fact:
          transmission_incomplete_dir: /mnt/media/transmission-incomplete
          transmission_default_download_dir: /mnt/media/movies
    - name: create transmission directories
      file:
        path: "{{ item }}"
        state: directory
        owner: htpc
      loop:
          - "{{ transmission_incomplete_dir }}"
          - "{{ transmission_default_download_dir }}"
    - name: stop transmission-daemon
      service: name=transmission-daemon state=stopped
    - name: copy transmission-daemon settings
      template:
        src: transmission-config.json
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
    - name: start transmission-daemon
      service: name=transmission-daemon state=started
